name = "coffee-app-api"
main = "worker.js"
compatibility_date = "2023-05-18"

# Configure KV namespaces for persistent storage
[[kv_namespaces]]
binding = "COFFEE_DB"
id = "create-this-in-cloudflare-dashboard" # Replace with actual ID from Cloudflare Dashboard

# Allow CORS for your frontend domain
[vars]
ALLOWED_ORIGIN = "https://coffee-app.pages.dev" # Replace with your actual frontend URL
