name = "coffee-app-api"
main = "worker.js"
compatibility_date = "2023-05-18"

# Deploy the worker
echo "Deploying worker to Cloudflare..."
wrangler deploy --name=coffee-app-api

cd ..

echo "=== Deployment complete ==="
echo "Your application is now deployed to Cloudflare!"
echo "Note: You may need to update your frontend to point to the Worker URL for API requests." 
