# docker-compose.yml
# Created on June 15 2023 by Florian Pfleiderer
# Copyright (c) MIT License

version: '3'

services:
  api:
    build: ./api
    ports:
      - 80:80

  frontend:
    build: .
    ports:
      - 3000:3000
