services:  
  api:
    build: 
      context: .
      dockerfile: Dockerfile.api
    image: florianpf/api
    # ports:
    #   - "127.0.0.1:5000:5000"

  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.frontend
    image: florianpf/frontend
    ports:
      - "3000:3000"
    links:
      - "api"