# docker-compose.yml
# Created on June 15 2023 by Florian Pfleiderer
# Copyright (c) MIT License

version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: api/Dockerfile
    container_name: api
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    environment:
      - FLASK_APP=api.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: .
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://api:8000
    depends_on:
      api:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
